language: 
  - go
  - ruby

go: 
  - 1.1

rvm:
  - 1.9.3-p484

before_install:
  - git submodule update --init --recursive

before_script:
  - gvm use go1.1

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/cloudfoundry/gosteno
  - go get -v github.com/howeyc/fsnotify
  - bundle install --without development

script: bin/test
